### ISSUE TITLE
Install command uses static "web" directory

### ISSUE THREAD

**Issue by sebastianneubert** [braincrafted/bootstrap.braincrafted.com#8]
Hi,

I'm not sure, if I'm here in the right place. I use the bootstrap bundle from packagist and want to use the install command for installing glyphicons.

``` json
    "scripts": {
        "post-install-cmd": [
            "Braincrafted\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::install"
    ]}
```

I found a hard copied string in the InstallCommand.php of the bundle. So my composer install fails, because my apache root dir isn't called "web".

``` php
         /* protected function class InstallCommand::getDestDir() */
        return sprintf(
            '%s/../web/%sfonts',
            $this->getContainer()->getParameter('kernel.root_dir'),
            $outputDir
        );
```

The output_dir configuration just put an extra string to the web dir. I expect, that I could use something like this in the config.yml:

``` yml
braincrafted_bootstrap:
    less_filter: lessphp
    output_dir: %kernel.root_dir%/../htdocs
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
```

Can I fork the bundle anywhere and use my own or change the code and send you a pull request?

Kind regards,
Sebastian
